-- FlatUI Dark (lkytal), adapted for Neovim from the working Appdesigner theme.
-- Put this file at ~/.config/nvim/colors/flatui.lua and run :colorscheme flatui.

vim.o.termguicolors = true
vim.o.background = 'dark'
vim.cmd.highlight('clear')
if vim.fn.exists('syntax_on') == 1 then
  vim.cmd('syntax reset')
end
vim.g.colors_name = 'flatui'

local c = {
  bg = '#222222',
  fg = '#cccccc',
  fg_soft = '#ABB2BF',
  line = '#3c424c',
  gutter = '#5C6370',
  comment = '#5C6370',
  blue = '#3193C6',
  blue_bright = '#61AFEF',
  green = '#05AD97',
  yellow = '#E5C07B',
  red = '#E06C75',
  purple = '#C678DD',
  orange = '#D19A66',
  cyan = '#56B6C2',
  cursor = '#528bff',
  error = '#F44747',
}

local set = vim.api.nvim_set_hl
local ui = {
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.bg },
  FloatBorder = { fg = c.gutter, bg = c.bg },
  FloatTitle = { fg = c.blue, bold = true },
  Cursor = { fg = c.bg, bg = c.cursor },
  CursorLine = { bg = c.line },
  CursorColumn = { bg = c.line },
  ColorColumn = { bg = c.line },
  LineNr = { fg = c.gutter },
  CursorLineNr = { fg = c.yellow, bold = true },
  SignColumn = { fg = c.gutter, bg = c.bg },
  FoldColumn = { fg = c.gutter, bg = c.bg },
  Folded = { fg = c.fg_soft, bg = c.line },
  Visual = { bg = c.line },
  Search = { fg = c.bg, bg = c.yellow },
  CurSearch = { fg = c.bg, bg = c.orange },
  IncSearch = { fg = c.bg, bg = c.orange },
  MatchParen = { fg = c.orange, bg = c.line, bold = true },
  StatusLine = { fg = c.fg, bg = c.line },
  StatusLineNC = { fg = c.gutter, bg = c.line },
  WinSeparator = { fg = c.line },
  VertSplit = { fg = c.line },
  Pmenu = { fg = c.fg, bg = c.line },
  PmenuSel = { fg = c.bg, bg = c.blue },
  PmenuSbar = { bg = c.line },
  PmenuThumb = { bg = c.gutter },
  TabLine = { fg = c.gutter, bg = c.bg },
  TabLineSel = { fg = c.fg, bg = c.line, bold = true },
  TabLineFill = { bg = c.bg },
  Directory = { fg = c.blue },
  Title = { fg = c.blue, bold = true },
  NonText = { fg = c.gutter },
  SpecialKey = { fg = c.gutter },
  Whitespace = { fg = '#4b525b' },
  ErrorMsg = { fg = c.error },
  WarningMsg = { fg = c.orange },
  MoreMsg = { fg = c.green },
  Question = { fg = c.green },
}

local syntax = {
  Comment = { fg = c.comment, italic = true },
  Constant = { fg = c.orange },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.orange },
  Boolean = { fg = c.orange },
  Float = { fg = c.orange },
  Identifier = { fg = c.green },
  Function = { fg = c.blue },
  Statement = { fg = c.red },
  Conditional = { fg = c.red },
  Repeat = { fg = c.red },
  Label = { fg = c.red },
  Operator = { fg = c.fg_soft },
  Keyword = { fg = c.red },
  Exception = { fg = c.red },
  PreProc = { fg = c.purple },
  Include = { fg = c.red },
  Define = { fg = c.purple },
  Macro = { fg = c.purple },
  PreCondit = { fg = c.purple },
  Type = { fg = c.yellow },
  StorageClass = { fg = c.purple },
  Structure = { fg = c.yellow },
  Typedef = { fg = c.yellow },
  Special = { fg = c.cyan },
  SpecialChar = { fg = c.cyan },
  Tag = { fg = c.red },
  Delimiter = { fg = c.fg_soft },
  SpecialComment = { fg = c.comment, italic = true },
  Debug = { fg = c.orange },
  Underlined = { fg = c.blue, underline = true },
  Error = { fg = '#FFFFFF', bg = c.error },
  Todo = { fg = c.yellow, bg = c.line, bold = true },
}

local treesitter = {
  ['@comment'] = { link = 'Comment' },
  ['@string'] = { link = 'String' },
  ['@string.escape'] = { fg = c.cyan },
  ['@string.regexp'] = { fg = c.cyan },
  ['@character'] = { link = 'Character' },
  ['@number'] = { link = 'Number' },
  ['@number.float'] = { link = 'Float' },
  ['@boolean'] = { link = 'Boolean' },
  ['@constant'] = { link = 'Constant' },
  ['@constant.builtin'] = { link = 'Constant' },
  ['@constant.macro'] = { fg = c.orange },
  ['@variable'] = { fg = c.green },
  ['@variable.builtin'] = { fg = c.yellow },
  ['@variable.parameter'] = { fg = c.green },
  ['@variable.member'] = { fg = c.green },
  ['@property'] = { fg = c.green },
  ['@field'] = { fg = c.green },
  ['@parameter'] = { fg = c.green },
  ['@function'] = { fg = c.blue },
  ['@function.call'] = { fg = c.blue },
  ['@function.method'] = { fg = c.blue },
  ['@function.method.call'] = { fg = c.blue },
  ['@function.builtin'] = { fg = c.cyan },
  ['@method'] = { fg = c.blue },
  ['@method.call'] = { fg = c.blue },
  ['@constructor'] = { fg = c.yellow },
  ['@type'] = { fg = c.yellow },
  ['@type.builtin'] = { fg = c.yellow },
  ['@type.definition'] = { fg = c.yellow },
  ['@class'] = { fg = c.yellow },
  ['@module'] = { fg = c.yellow },
  ['@namespace'] = { fg = c.yellow },
  ['@keyword'] = { fg = c.red },
  ['@keyword.function'] = { fg = c.purple },
  ['@keyword.storage'] = { fg = c.purple },
  ['@keyword.type'] = { fg = c.purple },
  ['@keyword.operator'] = { fg = c.fg_soft },
  ['@operator'] = { fg = c.fg_soft },
  ['@punctuation'] = { fg = c.fg_soft },
  ['@punctuation.bracket'] = { fg = c.fg_soft },
  ['@punctuation.delimiter'] = { fg = c.fg_soft },
  ['@tag'] = { fg = c.red },
  ['@tag.attribute'] = { fg = c.orange },
  ['@tag.delimiter'] = { fg = c.fg_soft },
}

local semantic = {
  ['@lsp.type.variable'] = { fg = c.green },
  ['@lsp.type.parameter'] = { fg = c.green },
  ['@lsp.type.property'] = { fg = c.green },
  ['@lsp.type.function'] = { fg = c.blue },
  ['@lsp.type.method'] = { fg = c.blue },
  ['@lsp.type.class'] = { fg = c.yellow },
  ['@lsp.type.interface'] = { fg = c.yellow },
  ['@lsp.type.enum'] = { fg = c.yellow },
  ['@lsp.type.type'] = { fg = c.yellow },
  ['@lsp.type.typeParameter'] = { fg = c.yellow },
  ['@lsp.type.namespace'] = { fg = c.yellow },
  ['@lsp.type.enumMember'] = { fg = c.orange },
  ['@lsp.type.selfKeyword'] = { fg = c.yellow },
  ['@lsp.type.number'] = { fg = c.orange },
  ['@lsp.type.string'] = { fg = c.green },
  ['@lsp.type.keyword'] = { fg = c.red },
}

local diagnostics = {
  DiagnosticError = { fg = c.error },
  DiagnosticWarn = { fg = c.orange },
  DiagnosticInfo = { fg = c.blue_bright },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { undercurl = true, sp = c.error },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.orange },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue_bright },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },
  DiffAdd = { fg = c.green, bg = '#20332f' },
  DiffChange = { fg = c.blue, bg = '#27313a' },
  DiffDelete = { fg = c.red, bg = '#3a272b' },
  DiffText = { fg = c.blue_bright, bg = c.line },
}

for _, groups in ipairs({ ui, syntax, treesitter, semantic, diagnostics }) do
  for name, style in pairs(groups) do
    set(0, name, style)
  end
end
